version: '2'
services:
  webapp:
    build: webapp/
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    build: redis/
    ports: 
      - "6379:6379"
  proxy:
    build: proxy/
    ports:
     - "3456:3456"
    depends_on:
    - redis